version: "3.8"
services:
  # MySQL database container
  database:
    image: mysql:8.0
    container_name: commerce_db
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_DATABASE: commerce
      MYSQL_ROOT_PASSWORD: commerce_pwd
      MYSQL_USER: commerce_user
      MYSQL_PASSWORD: commerce_pwd
    ports:
      - "3306:3306"
    networks:
      - commerce

  # phpMyAdmin container
  phpmyadmin:
    image: phpmyadmin:latest
    container_name: commerce_phpmyadmin
    restart: always
    depends_on:
      - database
    ports:
      - "8080:80"
    environment:
      PMA_HOST: database
    networks:
      - commerce

  # Symfony Apache project container (Back-end)
  backend:
    build: ./
    container_name: commerce_backend
    ports:
      - "8000:8000"
    volumes:
      - .:/var/www/html  # Symfony root directory
    restart: always
    environment:
      COMPOSER_ALLOW_SUPERUSER: 1
      DATABASE_URL: "mysql://commerce_user:commerce_pwd@database:3306/commerce?serverVersion=8.0&charset=utf8mb4"
    depends_on:
      - database
    command: bash -c "/usr/local/bin/docker-entrypoint.sh"
    networks:
      - commerce

networks:
  commerce:
